#! /bin/bash

nm --version 1> /dev/null 2>&1
echo $?

c++filt --version 1> /dev/null 2>&1
echo $?


echo "================================================="
echo "Symbols generated by variadic template - option A"
echo "-------------------------------------------------"
nm VariadicTemplateA | c++filt -t | grep toString
echo

echo "================================================="
echo "Symbols generated by variadic template - option B"
echo "-------------------------------------------------"
nm VariadicTemplateB | c++filt -t | grep toString
