#! /bin/bash

echo
echo "================================================="
echo "Dependencies"
echo "-------------------------------------------------"
if ERRMSG=$(nm --version 1> /dev/null 2>&1)
then
  echo "nm is installed."
else
  echo "error: Make sure you have nm installed."
  exit
fi

if ERRMSG=$(c++filt --version 1> /dev/null 2>&1)
then
  echo "c++filt is installed"
else
  echo "error: Make sure you have c++filt installed."
  exit
fi

echo
echo "================================================="
echo "Symbols generated by variadic template - option A"
echo "-------------------------------------------------"
nm VariadicTemplateA | c++filt -t | grep toString
echo

echo "================================================="
echo "Symbols generated by variadic template - option B"
echo "-------------------------------------------------"
nm VariadicTemplateB | c++filt -t | grep toString
