default: \
	si_build \
	si_run

si_build:
	@echo
	@echo ----------------------------------------------
	@echo Building SysInfo
	@echo ----------------------------------------------
	@echo
	@g++ main.cpp info-mac.cpp -std=c++17 -o sysinfo

si_run:
	@echo
	@echo ----------------------------------------------
	@echo Running SysInfo
	@echo ----------------------------------------------
	@echo
	@./sysinfo



