default: \
	si_build \
	si_run

si_build:
	@echo
	@echo ----------------------------------------------
	@echo Building Step3
	@echo ----------------------------------------------
	@echo
	@cl -nologo main.cpp -Festep3.exe -I. -EHsc

si_run:
	@echo
	@echo ----------------------------------------------
	@echo Running Step3
	@echo ----------------------------------------------
	@echo
	@step3.exe



